services:
  traefik:
    image: 'traefik:3.4'
    healthcheck:
      test:
        - CMD
        - traefik
        - healthcheck
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - traefik-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      - ./config/dynamic.yaml:/etc/traefik/dynamic.yaml
      - ./certs:/certs
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik-proxy:
    external: true
