version: '3'
services:
  traefik:
    image: 'traefik:3.0'
    healthcheck:
      test:
        - CMD
        - traefik
        - healthcheck
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - traefik-public
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      - ./certs:/certs
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: Host(`traefik-dashboard.rundemoapp.com`)
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.tls: true
      traefik.http.routers.dashboard.service: api@internal
networks:
  traefik-public:
    external: true
