services:
  app1:
    image: traefik/whoami:latest
    restart: always
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.app1.rule: Host(`traefik-demo-app1.rundemoapp.com`)
      traefik.http.routers.app1.entrypoints: websecure
      traefik.http.routers.app1.tls: true
      traefik.http.services.app1.loadbalancer.server.port: 80
  app2:
    image: traefik/whoami:latest
    restart: always
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.app2.rule: Host(`traefik-demo-app2.rundemoapp.com`) && Path(`/foo`)
      traefik.http.routers.app2.entrypoints: websecure
      traefik.http.routers.app2.tls: true
      traefik.http.services.app2.loadbalancer.server.port: 80

networks:
  traefik-proxy:
    external: true
