## DYNAMIC CONFIG

tls:
  certificates:
    - certFile: /certs/cloudflare_rundemoapp.crt
      keyFile: /certs/cloudflare_rundemoapp.key
# when troubleshooting certs, enable this so traefik doesn't use 
# its own self-signed. By default if it can't find a matching
# cert, it'll just create its own which will cause cert warnings
# in browser and can be confusing to troubleshoot
  # options:
    # default:
      # sniStrict: true
