## DYNAMIC CONFIG

# Dynamic HTTP configuration
http:
  # Routers for Traefik Dashboard
  routers:
    # Redirect dashboard HTTP to HTTPS
    dashboard-http-redirect:
      rule: "(PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      entryPoints:
        - "web"
      middlewares:
        - "dashboard-https-redirect"
      service: "api@internal"
    
    # Dashboard route via HTTPS only
    dashboard-https:
      rule: "(PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      entryPoints:
        - "websecure"
      middlewares:
        - "dashboard-redirect"
        - "dashboard-whitelist"
        - "cloudflare-realip"
      service: "api@internal"
      tls: {}

  # Middlewares
  middlewares:
    cloudflare-realip:
      headers:
        # Pass through original client IP headers from Cloudflare
        customRequestHeaders:
          # Cloudflare sends real IP in CF-Connecting-IP header
          X-Real-IP: "CF-Connecting-IP"
          # Keep original Cloudflare headers
          X-CF-Connecting-IP: "CF-Connecting-IP"
          X-CF-IPCountry: "CF-IPCountry"
        # Preserve host headers for proper routing
        hostsProxyHeaders:
          - "X-Forwarded-Host"
          - "X-Forwarded-Proto"
    
    # Basic Auth for Traefik Dashboard
    dashboard-auth:
      basicAuth:
        users:
          # admin:admin123 (change password as needed)
          - "admin:$apr1$iHxHQb/t$TCgjILm5WkEu8YSPNEUAV0"
          # user:user123
          - "user:$apr1$8kY3tJ9L$K2.vGaH3W.3d5aF5r3J8v."
    
    # IP Whitelist (optional) - Updated to include your network
    dashboard-whitelist:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"          # localhost
          - "10.0.0.0/8"            # Private network
          - "192.168.0.0/16"        # Private network
          - "172.16.0.0/12"         # Private network
          # - "0.0.0.0/0"             # Allow all (for testing - remove for production)
    
    # Redirect root to dashboard
    redirect-to-dashboard:
      redirectRegex:
        regex: "^(https?)://([^/]+)/?$"
        replacement: "${1}://${2}/dashboard/"
    
    # Add trailing slash to dashboard path
    dashboard-redirect:
      redirectRegex:
        regex: "^(https?)://([^/]+)/dashboard$"
        replacement: "${1}://${2}/dashboard/"
    
tls:
  certificates:
    - certFile: /certs/cloudflare_rundemoapp.crt
      keyFile: /certs/cloudflare_rundemoapp.key
# when troubleshooting certs, enable this so traefik doesn't use 
# its own self-signed. By default if it can't find a matching
# cert, it'll just create its own which will cause cert warnings
# in browser and can be confusing to troubleshoot
  # options:
    # default:
      # sniStrict: true
